name: utm
description: This is a Lat Lon and UTM bidirectional converter

# version: 1.0.0
# homepage: https://www.example.com
# author: tomoaki kanayama

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angles: ^1.2.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
